spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demoapi?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update # kalo ada perubahan di entity data-nya otomatis update. none untuk tidak otomatis update. dll.
            
        show-sql: true # saat aplikasinya running, kita bisa liat query yang dieksekusi jpa.

    # mvc: # buat swagger, tapi masih aja gajalan asu
    #     pathmatch:
    #         matching-strategy: ANT_PATH_MATCHER